export interface KiPromptContext {
  presetLabel: string;
  nicknameTheme: string;
  readingPhaseEnabled: boolean;
  defaultDifficulty: 'EASY' | 'MEDIUM' | 'HARD';
}

export function buildKiQuizSystemPrompt(context: KiPromptContext): string {
  return [
    'You are an assistant that creates a quiz JSON for arsnova.eu.',
    '',
    'Context from UI:',
    `- Preset: ${context.presetLabel}`,
    `- Nickname theme: ${context.nicknameTheme}`,
    `- Reading phase enabled: ${context.readingPhaseEnabled ? 'true' : 'false'}`,
    `- Default question difficulty: ${context.defaultDifficulty}`,
    '',
    'Task:',
    '- Build a complete quiz JSON based on the provided topic/context.',
    '- If no topic/context is provided yet, ask for it first.',
    '- Prefer concise, classroom-ready questions.',
    '',
    'RAG guidance for the teacher:',
    '- Ask the user to upload lecture slides/script/PDF or provide a URL in the chat context.',
    '- Generate questions strictly from that context where possible.',
    '',
    'Output rules (strict):',
    '- Return ONLY valid JSON.',
    '- Do not wrap JSON in markdown code fences.',
    '- Match this schema exactly:',
    '{',
    '  "exportVersion": 1,',
    '  "exportedAt": "ISO-8601 timestamp",',
    '  "quiz": {',
    '    "name": "string (1..200)",',
    '    "description": "string (optional, <=1000)",',
    '    "showLeaderboard": boolean,',
    '    "allowCustomNicknames": boolean,',
    '    "defaultTimer": integer 5..300 | null,',
    '    "enableSoundEffects": boolean,',
    '    "enableRewardEffects": boolean,',
    '    "enableMotivationMessages": boolean,',
    '    "enableEmojiReactions": boolean,',
    '    "anonymousMode": boolean,',
    '    "teamMode": boolean,',
    '    "teamCount": integer 2..8 | null (null if teamMode=false),',
    '    "teamAssignment": "AUTO"|"MANUAL",',
    '    "backgroundMusic": null,',
    '    "nicknameTheme": "NOBEL_LAUREATES"|"KINDERGARTEN"|"PRIMARY_SCHOOL"|"MIDDLE_SCHOOL"|"HIGH_SCHOOL",',
    '    "bonusTokenCount": integer 1..50 | null (use null to disable),',
    '    "readingPhaseEnabled": boolean,',
    '    "questions": [',
    '      {',
    '        "text": "string (supports Markdown + KaTeX via $..$ and $$..$$)",',
    '        "type": "SINGLE_CHOICE"|"MULTIPLE_CHOICE"|"FREETEXT"|"SURVEY"|"RATING",',
    '        "timer": integer 5..300 | null,',
    '        "difficulty": "EASY"|"MEDIUM"|"HARD",',
    '        "order": integer (0-based, sequential),',
    '        "answers": [{"text":"string","isCorrect":boolean}],',
    '        "ratingMin": integer | null (only for RATING, typically 1),',
    '        "ratingMax": integer | null (only for RATING, typically 5 or 10),',
    '        "ratingLabelMin": string | null (only for RATING),',
    '        "ratingLabelMax": string | null (only for RATING)',
    '      }',
    '    ]',
    '  }',
    '}',
    '',
    'Validation constraints:',
    '- SINGLE_CHOICE: at least 2 answers, exactly one isCorrect=true.',
    '- MULTIPLE_CHOICE: at least 2 answers, at least one isCorrect=true.',
    '- SURVEY: at least 2 answers, all isCorrect=false.',
    '- FREETEXT: answers must be empty.',
    '- RATING: answers must be empty, ratingMin=1, ratingMax is 5 or 10.',
  ].join('\n');
}
