/**
 * Clientseitige Nickname-Listen pro Thema (Story 3.2). Mind. 50 Einträge pro Thema.
 */
import type { NicknameTheme } from '@arsnova/shared-types';

export const NICKNAME_LISTS: Record<NicknameTheme, readonly string[]> = {
  NOBEL_LAUREATES: [
    'Marie Curie', 'Albert Einstein', 'Ada Yonath', 'Niels Bohr', 'Max Planck',
    'Erwin Schrödinger', 'Werner Heisenberg', 'Paul Dirac', 'Richard Feynman',
    'Linus Pauling', 'Dorothy Hodgkin', 'Maria Goeppert-Mayer', 'Emmanuelle Charpentier',
    'Jennifer Doudna', 'Frances Arnold', 'Donna Strickland', 'Gérard Mourou',
    'Arthur Ashkin', 'Kip Thorne', 'Barry Barish', 'Rainer Weiss', 'Peter Higgs',
    'François Englert', 'Andre Geim', 'Konstantin Novoselov', 'Elizabeth Blackburn',
    'Carol Greider', 'Jack Szostak', 'Roger Kornberg', 'Theodor Hänsch',
    'Roy Glauber', 'John Hall', 'Wolfgang Ketterle', 'Eric Cornell', 'Carl Wieman',
    'Steven Chu', 'Claude Cohen-Tannoudji', 'William Phillips', 'Robert Laughlin',
    'Horst Störmer', 'Daniel Tsui', 'Gerardus t Hooft', 'Martinus Veltman',
    'Robert Richardson', 'Douglas Osheroff', 'David Lee', 'Bertram Brockhouse',
    'Clifford Shull', 'Georges Charpak', 'Russell Hulse', 'Joseph Taylor',
    'Pierre-Gilles de Gennes', 'Jerome Friedman', 'Henry Kendall', 'Richard Taylor',
    'Leon Lederman', 'Melvin Schwartz', 'Jack Steinberger', 'Johannes Bednorz',
    'Karl Müller', 'Ernst Ruska', 'Gerd Binnig', 'Heinrich Rohrer',
  ],
  KINDERGARTEN: [
    'Blauer Elefant', 'Rotes Einhorn', 'Grüner Frosch', 'Gelber Löwe', 'Lila Delfin',
    'Oranger Fuchs', 'Rosa Schmetterling', 'Türkiser Wal', 'Brauner Bär', 'Schwarzer Panther',
    'Weißer Hase', 'Grauer Wolf', 'Goldener Fisch', 'Silberner Vogel', 'Bunter Papagei',
    'Hellblauer Schwan', 'Dunkelgrüne Schlange', 'Zitronengelbe Biene', 'Pfirsichfarbenes Pferd',
    'Mintgrüne Eidechse', 'Korallenroter Krebs', 'Himmelblauer Marienkäfer', 'Olivgrüne Maus',
    'Beiger Igel', 'Lachsfarbener Flamingo', 'Lavendelblaue Eule', 'Senfgelber Hahn',
    'Tannengrüner Biber', 'Himbeerroter Fuchs', 'Apfelgrüne Raupe', 'Maulwurfsgrauer Hamster',
    'Kastanienbraunes Pony', 'Azurblauer Schmetterling', 'Salbeigrünes Krokodil',
    'Terrakottafarbener Dachs', 'Smaragdgrüne Libelle', 'Amberfarbene Eule',
    'Smaragdgrüner Frosch', 'Kobaltblauer Delfin', 'Safrangelber Vogel', 'Indigoblauer Wal',
    'Khakifarbener Bär', 'Magenta Schildkröte', 'Ockerfarbener Igel', 'Petrolfarbener Fisch',
    'Pflaumenfarbener Vogel', 'Rubinroter Fuchs', 'Smaragdgrüne Schlange', 'Topasgelber Löwe',
    'Ultramarinblauer Schwan', 'Vanillefarbenes Lamm', 'Weinroter Papagei', 'Zinnoberroter Hahn',
    'Aquamarin Delfin', 'Bernsteinfarbener Bär', 'Chromgelber Schmetterling',
  ],
  PRIMARY_SCHOOL: [
    'Rotkäppchen', 'Rumpelstilzchen', 'Schneewittchen', 'Dornröschen', 'Aschenputtel',
    'Froschkönig', 'Hänsel', 'Gretel', 'Rapunzel', 'Frau Holle',
    'Schneeweißchen', 'Rosenrot', 'Der Wolf', 'Die sieben Geißlein', 'Der gestiefelte Kater',
    'Tischlein deck dich', 'Goldesel', 'Knüppel aus dem Sack', 'Sterntaler', 'Die Bremer Stadtmusikanten',
    'Der Hase', 'Der Igel', 'Der Fuchs', 'Der Bär', 'Das tapfere Schneiderlein',
    'Hans im Glück', 'Der süße Brei', 'Die Prinzessin auf der Erbse', 'Des Kaisers neue Kleider',
    'Der Froschkönig', 'Jorinde und Joringel', 'Allerleirauh', 'Die Gänsemagd',
    'Der Teufel mit den drei goldenen Haaren', 'Die goldene Gans', 'Brüderchen und Schwesterchen',
    'Der Eisenhans', 'Der goldene Vogel', 'Die sieben Raben', 'Die zwölf Brüder',
    'König Drosselbart', 'Märchen von einem der auszog', 'Der Mond', 'Die Sterntaler',
    'Schneeblume', 'König Lindwurm', 'Der kleine Däumling', 'Die weiße Schlange',
    'Der Arme und der Reiche', 'Das Wasser des Lebens', 'Der Räuberbräutigam',
    'Fundevogel', 'Die kluge Bauerntochter', 'Der alte Großvater', 'Die Wichtelmänner',
    'Die sieben Schwaben', 'Simeliberg', 'Der Trommler', 'Die Kristallkugel',
  ],
  MIDDLE_SCHOOL: [
    'Kolumbus', 'Amelia Earhart', 'Marco Polo', 'Neil Armstrong', 'Jacques Cousteau',
    'Edmund Hillary', 'Tenzing Norgay', 'Roald Amundsen', 'Robert Scott', 'Ferdinand Magellan',
    'Vasco da Gama', 'James Cook', 'Lewis und Clark', 'Sacagawea', 'David Livingstone',
    'Mary Kingsley', 'Ibn Battuta', 'Zheng He', 'Leif Erikson', 'Erik der Rote',
    'Francis Drake', 'Henry Hudson', 'Amerigo Vespucci', 'Hernán Cortés', 'Francisco Pizarro',
    'Alexander von Humboldt', 'Charles Darwin', 'Alfred Wegener', 'Thor Heyerdahl',
    'Yuri Gagarin', 'Valentina Tereschkowa', 'Sally Ride', 'Buzz Aldrin', 'John Glenn',
    'Alan Shepard', 'Bruce McCandless', 'Kalpana Chawla', 'Mae Jemison', 'Ellen Ochoa',
    'Superman', 'Batman', 'Wonder Woman', 'Spider-Man', 'Iron Man', 'Captain America',
    'Black Widow', 'Thor', 'Hulk', 'Black Panther', 'Captain Marvel', 'Ant-Man',
    'Wasp', 'Doctor Strange', 'Scarlet Witch', 'Vision', 'Falcon', 'Winter Soldier',
    'Hawkeye', 'Nick Fury', 'Loki', 'Groot', 'Rocket', 'Gamora', 'Drax', 'Star-Lord',
  ],
  HIGH_SCHOOL: [
    'Kant', 'Noether', 'Hawking', 'Leibniz', 'Newton', 'Descartes', 'Aristoteles',
    'Platon', 'Sokrates', 'Hegel', 'Schopenhauer', 'Nietzsche', 'Wittgenstein',
    'Russell', 'Popper', 'Kuhn', 'Feyerabend', 'Hume', 'Locke', 'Berkeley',
    'Spinoza', 'Rousseau', 'Voltaire', 'Montesquieu', 'Hobbes', 'Mill', 'Bentham',
    'Rawls', 'Habermas', 'Arendt', 'Heidegger', 'Sartre', 'Camus', 'Simone de Beauvoir',
    'Foucault', 'Derrida', 'Deleuze', 'Lacan', 'Freud', 'Jung', 'Adorno', 'Horkheimer',
    'Benjamin', 'Marcuse', 'Gadamer', 'Ricoeur', 'Levinas', 'Jonas', 'Apel',
    'Luhmann', 'Weber', 'Durkheim', 'Simmel', 'Mead', 'Goffman', 'Bourdieu',
    'Euclid', 'Archimedes', 'Pythagoras', 'Galileo', 'Kepler', 'Copernicus', 'Boyle',
    'Lavoisier', 'Dalton', 'Mendel', 'Darwin', 'Pasteur', 'Koch', 'Fleming',
  ],
};
